### PR TITLE
Merge with SD (add passive and array validator)

### PR DESCRIPTION
**Pull request by ljqx**
1. fixes of string and number validator.
2. passive and array validator and corresponding tests.

### CODE REVIEW

**Comment by ljqx** [comment]
@lyweiwei , this change adds passive validator which is needed by ko-schema.

**Comment by lyweiwei** [comment]
@ljqx could you add some test cases to silence coveralls?

**Comment by ljqx** [comment]
@lyweiwei , sure.

**Comment by ljqx** [comment]
@lyweiwei , I've imported some code of component/humanize in this PR, for keeping the coverage, I commented out unused code in it.

**Pull request merged**
